"""remove player_id field from Record

Revision ID: 44a646932be0
Revises: 4e03f54550f3
Create Date: 2021-02-14 02:38:49.178158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44a646932be0"
down_revision = "4e03f54550f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("record_player_id_fkey", "record", type_="foreignkey")
    op.drop_column("record", "player_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record",
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "record_player_id_fkey", "record", "player", ["player_id"], ["id"]
    )
    # ### end Alembic commands ###
