"""allow multi players per record

Revision ID: 90a91a94fc48
Revises: f1a4c52f2563
Create Date: 2021-02-13 22:54:07.120584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a91a94fc48"
down_revision = "f1a4c52f2563"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record_player_association",
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("record_player_association")
    # ### end Alembic commands ###
