"""add char/stage alias model

Revision ID: ab335a478550
Revises: 44a646932be0
Create Date: 2021-02-15 10:39:17.118166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab335a478550"
down_revision = "44a646932be0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_stage_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("stage_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_character_stage_alias_name"),
        "character_stage_alias",
        ["name"],
        unique=False,
    )
    op.create_table(
        "character_alias_assocation_table",
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("character_stage_alias_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_stage_alias_id"],
            ["character_stage_alias.id"],
        ),
    )
    op.create_table(
        "stage_alias_assocation_table",
        sa.Column("stage_id", sa.Integer(), nullable=True),
        sa.Column("character_stage_alias_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_stage_alias_id"],
            ["character_stage_alias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stage.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stage_alias_assocation_table")
    op.drop_table("character_alias_assocation_table")
    op.drop_index(
        op.f("ix_character_stage_alias_name"), table_name="character_stage_alias"
    )
    op.drop_table("character_stage_alias")
    # ### end Alembic commands ###
