"""make alias name unique

Revision ID: bcfd617f061a
Revises: ab335a478550
Create Date: 2021-02-15 11:10:57.616107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfd617f061a'
down_revision = 'ab335a478550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_alias_assocation_table')
    op.drop_table('stage_alias_assocation_table')
    op.drop_index('ix_character_stage_alias_name', table_name='character_stage_alias')
    op.create_index(op.f('ix_character_stage_alias_name'), 'character_stage_alias', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_stage_alias_name'), table_name='character_stage_alias')
    op.create_index('ix_character_stage_alias_name', 'character_stage_alias', ['name'], unique=False)
    op.create_table('stage_alias_assocation_table',
    sa.Column('stage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_stage_alias_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_stage_alias_id'], ['character_stage_alias.id'], name='stage_alias_assocation_table_character_stage_alias_id_fkey'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name='stage_alias_assocation_table_stage_id_fkey')
    )
    op.create_table('character_alias_assocation_table',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_stage_alias_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_alias_assocation_table_character_id_fkey'),
    sa.ForeignKeyConstraint(['character_stage_alias_id'], ['character_stage_alias.id'], name='character_alias_assocation_table_character_stage_alias_id_fkey')
    )
    # ### end Alembic commands ###
