"""add player alias model

Revision ID: c9264a2bbb80
Revises: bcfd617f061a
Create Date: 2021-02-15 11:57:23.140531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9264a2bbb80"
down_revision = "bcfd617f061a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_alias_name"), "player_alias", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_alias_name"), table_name="player_alias")
    op.drop_table("player_alias")
    # ### end Alembic commands ###
