"""add record and player models

Revision ID: d237f5738423
Revises: 915a2b6c681d
Create Date: 2021-02-13 20:13:56.173994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d237f5738423"
down_revision = "915a2b6c681d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_name"), "player", ["name"], unique=False)
    op.create_table(
        "stage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stage_name"), "stage", ["name"], unique=False)
    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("stage_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("partial_targets", sa.Integer(), nullable=True),
        sa.Column("video_link", sa.String(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["stage.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_record_date_created"), "record", ["date_created"], unique=False
    )
    op.create_index(
        op.f("ix_record_date_updated"), "record", ["date_updated"], unique=False
    )
    op.create_index(
        op.f("ix_record_partial_targets"), "record", ["partial_targets"], unique=False
    )
    op.create_index(op.f("ix_record_time"), "record", ["time"], unique=False)
    op.add_column("character", sa.Column("name", sa.String(), nullable=True))
    op.add_column("character", sa.Column("position", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_character_name"), "character", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_character_name"), table_name="character")
    op.drop_column("character", "position")
    op.drop_column("character", "name")
    op.drop_index(op.f("ix_record_time"), table_name="record")
    op.drop_index(op.f("ix_record_partial_targets"), table_name="record")
    op.drop_index(op.f("ix_record_date_updated"), table_name="record")
    op.drop_index(op.f("ix_record_date_created"), table_name="record")
    op.drop_table("record")
    op.drop_index(op.f("ix_stage_name"), table_name="stage")
    op.drop_table("stage")
    op.drop_index(op.f("ix_player_name"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
