"""fix fks

Revision ID: f1a4c52f2563
Revises: 857aad2f6c01
Create Date: 2021-02-13 22:24:06.508653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a4c52f2563'
down_revision = '857aad2f6c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'character', ['position'])
    op.drop_constraint('record_player_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'player', ['player_id'], ['id'])
    op.create_unique_constraint(None, 'stage', ['position'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='unique')
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_player_id_fkey', 'record', 'stage', ['player_id'], ['id'])
    op.drop_constraint(None, 'character', type_='unique')
    # ### end Alembic commands ###
